/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mock_RPMControl.h"

static const char* CMockString_RPMControl_compute = "RPMControl_compute";
static const char* CMockString_RPMControl_init = "RPMControl_init";
static const char* CMockString_currRPM = "currRPM";
static const char* CMockString_maxDuty = "maxDuty";
static const char* CMockString_minDuty = "minDuty";
static const char* CMockString_targetRPM = "targetRPM";
static const char* CMockString_thHighRPM = "thHighRPM";
static const char* CMockString_thLowRPM = "thLowRPM";

typedef struct _CMOCK_RPMControl_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  unsigned char Expected_minDuty;
  unsigned char Expected_maxDuty;
  int Expected_targetRPM;
  int Expected_thHighRPM;
  int Expected_thLowRPM;
  int IgnoreArg_minDuty;
  int IgnoreArg_maxDuty;
  int IgnoreArg_targetRPM;
  int IgnoreArg_thHighRPM;
  int IgnoreArg_thLowRPM;

} CMOCK_RPMControl_init_CALL_INSTANCE;

typedef struct _CMOCK_RPMControl_compute_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  unsigned char ReturnVal;
  int Expected_currRPM;
  int IgnoreArg_currRPM;

} CMOCK_RPMControl_compute_CALL_INSTANCE;

static struct Mock_RPMControlInstance
{
  int RPMControl_init_IgnoreBool;
  CMOCK_RPMControl_init_CALLBACK RPMControl_init_CallbackFunctionPointer;
  int RPMControl_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE RPMControl_init_CallInstance;
  int RPMControl_compute_IgnoreBool;
  unsigned char RPMControl_compute_FinalReturn;
  CMOCK_RPMControl_compute_CALLBACK RPMControl_compute_CallbackFunctionPointer;
  int RPMControl_compute_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE RPMControl_compute_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mock_RPMControl_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.RPMControl_init_IgnoreBool)
    Mock.RPMControl_init_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_RPMControl_init);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.RPMControl_init_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.RPMControl_init_CallbackFunctionPointer != NULL)
    Mock.RPMControl_init_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.RPMControl_compute_IgnoreBool)
    Mock.RPMControl_compute_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_RPMControl_compute);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.RPMControl_compute_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.RPMControl_compute_CallbackFunctionPointer != NULL)
    Mock.RPMControl_compute_CallInstance = CMOCK_GUTS_NONE;
}

void Mock_RPMControl_Init(void)
{
  Mock_RPMControl_Destroy();
}

void Mock_RPMControl_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.RPMControl_init_CallbackFunctionPointer = NULL;
  Mock.RPMControl_init_CallbackCalls = 0;
  Mock.RPMControl_compute_CallbackFunctionPointer = NULL;
  Mock.RPMControl_compute_CallbackCalls = 0;
}

void RPMControl_init(unsigned char minDuty, unsigned char maxDuty, int targetRPM, int thHighRPM, int thLowRPM)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_RPMControl_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_RPMControl_init);
  cmock_call_instance = (CMOCK_RPMControl_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.RPMControl_init_CallInstance);
  Mock.RPMControl_init_CallInstance = CMock_Guts_MemNext(Mock.RPMControl_init_CallInstance);
  if (Mock.RPMControl_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_minDuty)
  {
    UNITY_SET_DETAILS(CMockString_RPMControl_init,CMockString_minDuty);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_minDuty, minDuty, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_maxDuty)
  {
    UNITY_SET_DETAILS(CMockString_RPMControl_init,CMockString_maxDuty);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_maxDuty, maxDuty, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_targetRPM)
  {
    UNITY_SET_DETAILS(CMockString_RPMControl_init,CMockString_targetRPM);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_targetRPM, targetRPM, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_thHighRPM)
  {
    UNITY_SET_DETAILS(CMockString_RPMControl_init,CMockString_thHighRPM);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_thHighRPM, thHighRPM, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_thLowRPM)
  {
    UNITY_SET_DETAILS(CMockString_RPMControl_init,CMockString_thLowRPM);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_thLowRPM, thLowRPM, cmock_line, CMockStringMismatch);
  }
  if (Mock.RPMControl_init_CallbackFunctionPointer != NULL)
  {
    Mock.RPMControl_init_CallbackFunctionPointer(minDuty, maxDuty, targetRPM, thHighRPM, thLowRPM, Mock.RPMControl_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_RPMControl_init(CMOCK_RPMControl_init_CALL_INSTANCE* cmock_call_instance, unsigned char minDuty, unsigned char maxDuty, int targetRPM, int thHighRPM, int thLowRPM)
{
  cmock_call_instance->Expected_minDuty = minDuty;
  cmock_call_instance->IgnoreArg_minDuty = 0;
  cmock_call_instance->Expected_maxDuty = maxDuty;
  cmock_call_instance->IgnoreArg_maxDuty = 0;
  cmock_call_instance->Expected_targetRPM = targetRPM;
  cmock_call_instance->IgnoreArg_targetRPM = 0;
  cmock_call_instance->Expected_thHighRPM = thHighRPM;
  cmock_call_instance->IgnoreArg_thHighRPM = 0;
  cmock_call_instance->Expected_thLowRPM = thLowRPM;
  cmock_call_instance->IgnoreArg_thLowRPM = 0;
}

void RPMControl_init_CMockIgnore(void)
{
  Mock.RPMControl_init_IgnoreBool = (int)1;
}

void RPMControl_init_CMockExpect(UNITY_LINE_TYPE cmock_line, unsigned char minDuty, unsigned char maxDuty, int targetRPM, int thHighRPM, int thLowRPM)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_RPMControl_init_CALL_INSTANCE));
  CMOCK_RPMControl_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_RPMControl_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.RPMControl_init_CallInstance = CMock_Guts_MemChain(Mock.RPMControl_init_CallInstance, cmock_guts_index);
  Mock.RPMControl_init_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_RPMControl_init(cmock_call_instance, minDuty, maxDuty, targetRPM, thHighRPM, thLowRPM);
  UNITY_CLR_DETAILS();
}

void RPMControl_init_StubWithCallback(CMOCK_RPMControl_init_CALLBACK Callback)
{
  Mock.RPMControl_init_IgnoreBool = (int)0;
  Mock.RPMControl_init_CallbackFunctionPointer = Callback;
}

void RPMControl_init_CMockIgnoreArg_minDuty(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_RPMControl_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_RPMControl_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.RPMControl_init_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_minDuty = 1;
}

void RPMControl_init_CMockIgnoreArg_maxDuty(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_RPMControl_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_RPMControl_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.RPMControl_init_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_maxDuty = 1;
}

void RPMControl_init_CMockIgnoreArg_targetRPM(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_RPMControl_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_RPMControl_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.RPMControl_init_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_targetRPM = 1;
}

void RPMControl_init_CMockIgnoreArg_thHighRPM(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_RPMControl_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_RPMControl_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.RPMControl_init_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_thHighRPM = 1;
}

void RPMControl_init_CMockIgnoreArg_thLowRPM(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_RPMControl_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_RPMControl_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.RPMControl_init_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_thLowRPM = 1;
}

unsigned char RPMControl_compute(int currRPM)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_RPMControl_compute_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_RPMControl_compute);
  cmock_call_instance = (CMOCK_RPMControl_compute_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.RPMControl_compute_CallInstance);
  Mock.RPMControl_compute_CallInstance = CMock_Guts_MemNext(Mock.RPMControl_compute_CallInstance);
  if (Mock.RPMControl_compute_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.RPMControl_compute_FinalReturn;
    Mock.RPMControl_compute_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_currRPM)
  {
    UNITY_SET_DETAILS(CMockString_RPMControl_compute,CMockString_currRPM);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_currRPM, currRPM, cmock_line, CMockStringMismatch);
  }
  if (Mock.RPMControl_compute_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.RPMControl_compute_CallbackFunctionPointer(currRPM, Mock.RPMControl_compute_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_RPMControl_compute(CMOCK_RPMControl_compute_CALL_INSTANCE* cmock_call_instance, int currRPM)
{
  cmock_call_instance->Expected_currRPM = currRPM;
  cmock_call_instance->IgnoreArg_currRPM = 0;
}

void RPMControl_compute_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, unsigned char cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_RPMControl_compute_CALL_INSTANCE));
  CMOCK_RPMControl_compute_CALL_INSTANCE* cmock_call_instance = (CMOCK_RPMControl_compute_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.RPMControl_compute_CallInstance = CMock_Guts_MemChain(Mock.RPMControl_compute_CallInstance, cmock_guts_index);
  Mock.RPMControl_compute_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.RPMControl_compute_IgnoreBool = (int)1;
}

void RPMControl_compute_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int currRPM, unsigned char cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_RPMControl_compute_CALL_INSTANCE));
  CMOCK_RPMControl_compute_CALL_INSTANCE* cmock_call_instance = (CMOCK_RPMControl_compute_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.RPMControl_compute_CallInstance = CMock_Guts_MemChain(Mock.RPMControl_compute_CallInstance, cmock_guts_index);
  Mock.RPMControl_compute_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_RPMControl_compute(cmock_call_instance, currRPM);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void RPMControl_compute_StubWithCallback(CMOCK_RPMControl_compute_CALLBACK Callback)
{
  Mock.RPMControl_compute_IgnoreBool = (int)0;
  Mock.RPMControl_compute_CallbackFunctionPointer = Callback;
}

void RPMControl_compute_CMockIgnoreArg_currRPM(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_RPMControl_compute_CALL_INSTANCE* cmock_call_instance = (CMOCK_RPMControl_compute_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.RPMControl_compute_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_currRPM = 1;
}

