/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mock_TempSensor.h"

static const char* CMockString_TempSensor_init = "TempSensor_init";

typedef struct _CMOCK_TempSensor_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  TempSensor* ReturnVal;

} CMOCK_TempSensor_init_CALL_INSTANCE;

static struct Mock_TempSensorInstance
{
  int TempSensor_init_IgnoreBool;
  TempSensor* TempSensor_init_FinalReturn;
  CMOCK_TempSensor_init_CALLBACK TempSensor_init_CallbackFunctionPointer;
  int TempSensor_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE TempSensor_init_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mock_TempSensor_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.TempSensor_init_IgnoreBool)
    Mock.TempSensor_init_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_TempSensor_init);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.TempSensor_init_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.TempSensor_init_CallbackFunctionPointer != NULL)
    Mock.TempSensor_init_CallInstance = CMOCK_GUTS_NONE;
}

void Mock_TempSensor_Init(void)
{
  Mock_TempSensor_Destroy();
}

void Mock_TempSensor_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.TempSensor_init_CallbackFunctionPointer = NULL;
  Mock.TempSensor_init_CallbackCalls = 0;
}

TempSensor* TempSensor_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_TempSensor_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_TempSensor_init);
  cmock_call_instance = (CMOCK_TempSensor_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.TempSensor_init_CallInstance);
  Mock.TempSensor_init_CallInstance = CMock_Guts_MemNext(Mock.TempSensor_init_CallInstance);
  if (Mock.TempSensor_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.TempSensor_init_FinalReturn;
    Mock.TempSensor_init_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.TempSensor_init_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.TempSensor_init_CallbackFunctionPointer(Mock.TempSensor_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void TempSensor_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, TempSensor* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TempSensor_init_CALL_INSTANCE));
  CMOCK_TempSensor_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_TempSensor_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TempSensor_init_CallInstance = CMock_Guts_MemChain(Mock.TempSensor_init_CallInstance, cmock_guts_index);
  Mock.TempSensor_init_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.TempSensor_init_IgnoreBool = (int)1;
}

void TempSensor_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, TempSensor* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TempSensor_init_CALL_INSTANCE));
  CMOCK_TempSensor_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_TempSensor_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TempSensor_init_CallInstance = CMock_Guts_MemChain(Mock.TempSensor_init_CallInstance, cmock_guts_index);
  Mock.TempSensor_init_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void TempSensor_init_StubWithCallback(CMOCK_TempSensor_init_CALLBACK Callback)
{
  Mock.TempSensor_init_IgnoreBool = (int)0;
  Mock.TempSensor_init_CallbackFunctionPointer = Callback;
}

