/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_THROTTLESENSOR_H
#define _MOCK_THROTTLESENSOR_H

#include "ThrottleSensor.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mock_ThrottleSensor_Init(void);
void Mock_ThrottleSensor_Destroy(void);
void Mock_ThrottleSensor_Verify(void);




#define ThrottleSensor_init_IgnoreAndReturn(cmock_retval) ThrottleSensor_init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void ThrottleSensor_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, ThrottleSensor* cmock_to_return);
#define ThrottleSensor_init_ExpectAndReturn(cmock_retval) ThrottleSensor_init_CMockExpectAndReturn(__LINE__, cmock_retval)
void ThrottleSensor_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ThrottleSensor* cmock_to_return);
typedef ThrottleSensor* (* CMOCK_ThrottleSensor_init_CALLBACK)(int cmock_num_calls);
void ThrottleSensor_init_StubWithCallback(CMOCK_ThrottleSensor_init_CALLBACK Callback);

#endif
