/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_RPMSENSOR_H
#define _MOCK_RPMSENSOR_H

#include "RPMSensor.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mock_RPMSensor_Init(void);
void Mock_RPMSensor_Destroy(void);
void Mock_RPMSensor_Verify(void);




#define RPMSensor_init_IgnoreAndReturn(cmock_retval) RPMSensor_init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void RPMSensor_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, RPMSensor* cmock_to_return);
#define RPMSensor_init_ExpectAndReturn(cmock_retval) RPMSensor_init_CMockExpectAndReturn(__LINE__, cmock_retval)
void RPMSensor_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RPMSensor* cmock_to_return);
typedef RPMSensor* (* CMOCK_RPMSensor_init_CALLBACK)(int cmock_num_calls);
void RPMSensor_init_StubWithCallback(CMOCK_RPMSensor_init_CALLBACK Callback);

#endif
