/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_TEMPSENSOR_H
#define _MOCK_TEMPSENSOR_H

#include "TempSensor.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mock_TempSensor_Init(void);
void Mock_TempSensor_Destroy(void);
void Mock_TempSensor_Verify(void);




#define TempSensor_init_IgnoreAndReturn(cmock_retval) TempSensor_init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void TempSensor_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, TempSensor* cmock_to_return);
#define TempSensor_init_ExpectAndReturn(cmock_retval) TempSensor_init_CMockExpectAndReturn(__LINE__, cmock_retval)
void TempSensor_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, TempSensor* cmock_to_return);
typedef TempSensor* (* CMOCK_TempSensor_init_CALLBACK)(int cmock_num_calls);
void TempSensor_init_StubWithCallback(CMOCK_TempSensor_init_CALLBACK Callback);

#endif
