/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_PWMINYECTOR_H
#define _MOCK_PWMINYECTOR_H

#include "PWMInyector.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mock_PWMInyector_Init(void);
void Mock_PWMInyector_Destroy(void);
void Mock_PWMInyector_Verify(void);




#define PWMInyector_init_Ignore() PWMInyector_init_CMockIgnore()
void PWMInyector_init_CMockIgnore(void);
#define PWMInyector_init_Expect() PWMInyector_init_CMockExpect(__LINE__)
void PWMInyector_init_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_PWMInyector_init_CALLBACK)(int cmock_num_calls);
void PWMInyector_init_StubWithCallback(CMOCK_PWMInyector_init_CALLBACK Callback);
#define PWMInyector_setDuty_Ignore() PWMInyector_setDuty_CMockIgnore()
void PWMInyector_setDuty_CMockIgnore(void);
#define PWMInyector_setDuty_Expect(duty) PWMInyector_setDuty_CMockExpect(__LINE__, duty)
void PWMInyector_setDuty_CMockExpect(UNITY_LINE_TYPE cmock_line, unsigned char duty);
typedef void (* CMOCK_PWMInyector_setDuty_CALLBACK)(unsigned char duty, int cmock_num_calls);
void PWMInyector_setDuty_StubWithCallback(CMOCK_PWMInyector_setDuty_CALLBACK Callback);
#define PWMInyector_setDuty_IgnoreArg_duty() PWMInyector_setDuty_CMockIgnoreArg_duty(__LINE__)
void PWMInyector_setDuty_CMockIgnoreArg_duty(UNITY_LINE_TYPE cmock_line);

#endif
