/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_SENSOR_H
#define _MOCK_SENSOR_H

#include "Sensor.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mock_Sensor_Init(void);
void Mock_Sensor_Destroy(void);
void Mock_Sensor_Verify(void);




#define Sensor_get_IgnoreAndReturn(cmock_retval) Sensor_get_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void Sensor_get_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define Sensor_get_ExpectAndReturn(me, cmock_retval) Sensor_get_CMockExpectAndReturn(__LINE__, me, cmock_retval)
void Sensor_get_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, Sensor* const me, int cmock_to_return);
typedef int (* CMOCK_Sensor_get_CALLBACK)(Sensor* const me, int cmock_num_calls);
void Sensor_get_StubWithCallback(CMOCK_Sensor_get_CALLBACK Callback);
#define Sensor_get_IgnoreArg_me() Sensor_get_CMockIgnoreArg_me(__LINE__)
void Sensor_get_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);

#endif
