/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_TIMER_H
#define _MOCK_TIMER_H

#include "Timer.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mock_Timer_Init(void);
void Mock_Timer_Destroy(void);
void Mock_Timer_Verify(void);




#define Timer_init_IgnoreAndReturn(cmock_retval) Timer_init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void Timer_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, Timer* cmock_to_return);
#define Timer_init_ExpectAndReturn(count, period, eventSignal, cmock_retval) Timer_init_CMockExpectAndReturn(__LINE__, count, period, eventSignal, cmock_retval)
void Timer_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int count, int period, int eventSignal, Timer* cmock_to_return);
typedef Timer* (* CMOCK_Timer_init_CALLBACK)(int count, int period, int eventSignal, int cmock_num_calls);
void Timer_init_StubWithCallback(CMOCK_Timer_init_CALLBACK Callback);
#define Timer_init_IgnoreArg_count() Timer_init_CMockIgnoreArg_count(__LINE__)
void Timer_init_CMockIgnoreArg_count(UNITY_LINE_TYPE cmock_line);
#define Timer_init_IgnoreArg_period() Timer_init_CMockIgnoreArg_period(__LINE__)
void Timer_init_CMockIgnoreArg_period(UNITY_LINE_TYPE cmock_line);
#define Timer_init_IgnoreArg_eventSignal() Timer_init_CMockIgnoreArg_eventSignal(__LINE__)
void Timer_init_CMockIgnoreArg_eventSignal(UNITY_LINE_TYPE cmock_line);
#define Timer_start_Ignore() Timer_start_CMockIgnore()
void Timer_start_CMockIgnore(void);
#define Timer_start_Expect(me) Timer_start_CMockExpect(__LINE__, me)
void Timer_start_CMockExpect(UNITY_LINE_TYPE cmock_line, Timer* const me);
typedef void (* CMOCK_Timer_start_CALLBACK)(Timer* const me, int cmock_num_calls);
void Timer_start_StubWithCallback(CMOCK_Timer_start_CALLBACK Callback);
#define Timer_start_IgnoreArg_me() Timer_start_CMockIgnoreArg_me(__LINE__)
void Timer_start_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);

#endif
