/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_INYECTORCONTROLACT_H
#define _MOCK_INYECTORCONTROLACT_H

#include "InyectorControlAct.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mock_InyectorControlAct_Init(void);
void Mock_InyectorControlAct_Destroy(void);
void Mock_InyectorControlAct_Verify(void);




#define InyectorControlAct_init_Ignore() InyectorControlAct_init_CMockIgnore()
void InyectorControlAct_init_CMockIgnore(void);
#define InyectorControlAct_init_Expect() InyectorControlAct_init_CMockExpect(__LINE__)
void InyectorControlAct_init_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_InyectorControlAct_init_CALLBACK)(int cmock_num_calls);
void InyectorControlAct_init_StubWithCallback(CMOCK_InyectorControlAct_init_CALLBACK Callback);
#define InyectorControlAct_starting_Ignore() InyectorControlAct_starting_CMockIgnore()
void InyectorControlAct_starting_CMockIgnore(void);
#define InyectorControlAct_starting_Expect(event) InyectorControlAct_starting_CMockExpect(__LINE__, event)
void InyectorControlAct_starting_CMockExpect(UNITY_LINE_TYPE cmock_line, Event* event);
typedef void (* CMOCK_InyectorControlAct_starting_CALLBACK)(Event* event, int cmock_num_calls);
void InyectorControlAct_starting_StubWithCallback(CMOCK_InyectorControlAct_starting_CALLBACK Callback);
#define InyectorControlAct_starting_IgnoreArg_event() InyectorControlAct_starting_CMockIgnoreArg_event(__LINE__)
void InyectorControlAct_starting_CMockIgnoreArg_event(UNITY_LINE_TYPE cmock_line);

#endif
